# GitHub workflow to enable continuous integratoin
name: Continuous Integration

# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: pwd
      run: pwd
    - name: ls
      run: ls -lha
    - name: mkdir bin
      run: |
      mkdir bin
      cd bin
      pwd
      ls
    - name: cmake
      run: cmake ..
    - name: make
      run: make
    - name: make test
      run: make test
