# GitHub workflow to enable continuous integratoin
name: Continuous Integration

# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - name: actions/checkout@master
    - name: mkdir bin
      run: mkdir bin; cd bin
    - name: cmake
      run: cmake ..
    - name: make
      run: make
    - name: make test
      run: make test
