# GitHub workflow to enable continuous integratoin
name: Continuous Integration

# This workflow is triggered on pushes to the repository.
on: 
  push:
    branches: '*'
  pull_request: 
    branches: '*'

runs-on: ${{matrix.os}}
strategy:
  matrix:
    os: [ubuntu-18.04, macOS]
jobs:
  build:
    name: "Testing"
    steps:
    - name: Install gfortran
      run: sudo apt-get install gfortran
    - uses: actions/checkout@v2
    - name: mkdir bin
      run: mkdir bin 
    - name: cmake
      run: cmake ..  
      working-directory: ./bin
    - name: make
      run: make -j
      working-directory: ./bin
    - name: ctest
      run: ctest -j
      working-directory: ./bin
