# GitHub workflow to enable continuous integratoin
name: Continuous Integration

# This workflow is triggered on pushes to the repository.
on: 
  push:
    branches: '*'
  pull_request: 
    branches: '*'

env:
  vFortran: gfortran-8

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        build_type: [ Debug, Release ]

    steps:
    - name: which gfortran
      run: |
        which #{{vFortran}}
        #{{vFortran}} --version
    - uses: actions/checkout@v2
    - name: mkdir bin
      run: mkdir bin 
    - name: cmake
      run: cmake -D CMAKE_Fortran_COMPILER=`which ${{vFortran}}` -D CMAKE_BUILD_TYPE=${{env.build_type}} ..  
      working-directory: ./bin
    - name: make
      run: make -j
      working-directory: ./bin
    - name: ctest
      run: ctest -V -j
      working-directory: ./bin
