# GitHub workflow to enable continuous integratoin
name: Continuous Integration

# This workflow is triggered on pushes to the repository.
on: 
  push:
    branches: '*'
  pull_request: 
    branches: '*'

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
        - os: ubuntu-latest
          vFortran: gfortran-9
        - os: macos-latest
          vFortran: gfortran

    steps:
    - name: which gfortran
      run: |
        which ${{matrix.vFortran}}
        ${{matrix.vFortran}} --version
    - uses: actions/checkout@v2
    - name: mkdir bin
      run: mkdir bin 
    - name: cmake
      run: cmake -D CMAKE_Fortran_COMPILER=`which ${{matrix.vFortran}} ..  
      working-directory: ./bin
    - name: make
      run: make -j
      working-directory: ./bin
    # - name: ctest
    #   run: ctest -j
    #   working-directory: ./bin
