# GitHub workflow to enable continuous integratoin
name: Continuous Integration

# This workflow is triggered on pushes to the repository.
on: 
  push:
    branches: '*'
  pull_request: 
    branches: '*'

jobs:
  build:
  name: Testing
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: mkdir bin
    run: mkdir bin; cd bin
  - name: cmake
    run: cmake ..  
  - name: make
    run: make
  - name: make test
    run: make test
