# GitHub workflow to enable continuous integratoin
name: Continuous Integration

# This workflow is triggered on pushes to the repository.
on: 
  push:
    branches: '*'
  pull_request: 
    branches: '*'

jobs:
  build:
    name: "Testing"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: mkdir bin
      run: mkdir bin 
    - name: cmake
      run: cmake ..  
      working-directory: ./bin
    - name: make
      run: make
      working-directory: ./bin
    - name: make test
      run: make test
      working-directory: ./bin
